sudo: required
dist: trusty
language: node_js
node_js: 8
cache: npm
branches:
  only:
  - master
jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: tsc
      script: npm run tsc
